{
  "timestamp": "2025-06-24T23:45:19.728219",
  "duration": 3.0058369636535645,
  "results": {
    "unit": {
      "total": 0,
      "passed": 0,
      "failed": 0,
      "tests": [
        {
          "name": "test_phase_manager.py",
          "success": false,
          "total": 0,
          "passed": 0,
          "failed": 0,
          "skipped": 0,
          "duration": 0.0,
          "output": "",
          "errors": "Traceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pytest/__main__.py\", line 5, in <module>\n    raise SystemExit(pytest.console_main())\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 192, in console_main\n    code = main()\n           ^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 150, in main\n    config = _prepareconfig(args, plugins)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 331, in _prepareconfig\n    config = pluginmanager.hook.pytest_cmdline_parse(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_callers.py\", line 55, in _multicall\n    gen.send(outcome)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/helpconfig.py\", line 104, in pytest_cmdline_parse\n    config: Config = outcome.get_result()\n                     ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1075, in pytest_cmdline_parse\n    self.parse(args)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1425, in parse\n    self._preparse(args, addopts=addopts)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1300, in _preparse\n    self._consider_importhook(args)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1204, in _consider_importhook\n    self._mark_plugins_for_rewrite(hook)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1224, in _mark_plugins_for_rewrite\n    for name in _iter_rewritable_modules(package_files):\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 863, in _iter_rewritable_modules\n    package_files = list(package_files)\n                    ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1221, in <genexpr>\n    for file in dist.files or []\n                ^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/importlib/metadata/__init__.py\", line 501, in files\n    make_files(\n  File \"/Users/bill/anaconda3/lib/python3.12/importlib/metadata/_functools.py\", line 102, in wrapper\n    return func(param, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/importlib/metadata/__init__.py\", line 494, in make_files\n    return starmap(make_file, csv.reader(lines))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: 'NoneType' object is not iterable\n"
        },
        {
          "name": "test_security_manager.py",
          "success": false,
          "total": 0,
          "passed": 0,
          "failed": 0,
          "skipped": 0,
          "duration": 0.0,
          "output": "",
          "errors": "Traceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pytest/__main__.py\", line 5, in <module>\n    raise SystemExit(pytest.console_main())\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 192, in console_main\n    code = main()\n           ^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 150, in main\n    config = _prepareconfig(args, plugins)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 331, in _prepareconfig\n    config = pluginmanager.hook.pytest_cmdline_parse(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_callers.py\", line 55, in _multicall\n    gen.send(outcome)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/helpconfig.py\", line 104, in pytest_cmdline_parse\n    config: Config = outcome.get_result()\n                     ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1075, in pytest_cmdline_parse\n    self.parse(args)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1425, in parse\n    self._preparse(args, addopts=addopts)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1300, in _preparse\n    self._consider_importhook(args)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1204, in _consider_importhook\n    self._mark_plugins_for_rewrite(hook)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1224, in _mark_plugins_for_rewrite\n    for name in _iter_rewritable_modules(package_files):\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 863, in _iter_rewritable_modules\n    package_files = list(package_files)\n                    ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1221, in <genexpr>\n    for file in dist.files or []\n                ^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/importlib/metadata/__init__.py\", line 501, in files\n    make_files(\n  File \"/Users/bill/anaconda3/lib/python3.12/importlib/metadata/_functools.py\", line 102, in wrapper\n    return func(param, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/importlib/metadata/__init__.py\", line 494, in make_files\n    return starmap(make_file, csv.reader(lines))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: 'NoneType' object is not iterable\n"
        },
        {
          "name": "test_firewall_manager.py",
          "success": false,
          "total": 0,
          "passed": 0,
          "failed": 0,
          "skipped": 0,
          "duration": 0.0,
          "output": "",
          "errors": "Traceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pytest/__main__.py\", line 5, in <module>\n    raise SystemExit(pytest.console_main())\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 192, in console_main\n    code = main()\n           ^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 150, in main\n    config = _prepareconfig(args, plugins)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 331, in _prepareconfig\n    config = pluginmanager.hook.pytest_cmdline_parse(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_callers.py\", line 55, in _multicall\n    gen.send(outcome)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/helpconfig.py\", line 104, in pytest_cmdline_parse\n    config: Config = outcome.get_result()\n                     ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1075, in pytest_cmdline_parse\n    self.parse(args)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1425, in parse\n    self._preparse(args, addopts=addopts)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1300, in _preparse\n    self._consider_importhook(args)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1204, in _consider_importhook\n    self._mark_plugins_for_rewrite(hook)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1224, in _mark_plugins_for_rewrite\n    for name in _iter_rewritable_modules(package_files):\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 863, in _iter_rewritable_modules\n    package_files = list(package_files)\n                    ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1221, in <genexpr>\n    for file in dist.files or []\n                ^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/importlib/metadata/__init__.py\", line 501, in files\n    make_files(\n  File \"/Users/bill/anaconda3/lib/python3.12/importlib/metadata/_functools.py\", line 102, in wrapper\n    return func(param, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/importlib/metadata/__init__.py\", line 494, in make_files\n    return starmap(make_file, csv.reader(lines))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: 'NoneType' object is not iterable\n"
        },
        {
          "name": "test_dashboard_server.py",
          "success": false,
          "total": 0,
          "passed": 0,
          "failed": 0,
          "skipped": 0,
          "duration": 0.0,
          "output": "",
          "errors": "Traceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pytest/__main__.py\", line 5, in <module>\n    raise SystemExit(pytest.console_main())\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 192, in console_main\n    code = main()\n           ^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 150, in main\n    config = _prepareconfig(args, plugins)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 331, in _prepareconfig\n    config = pluginmanager.hook.pytest_cmdline_parse(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_callers.py\", line 55, in _multicall\n    gen.send(outcome)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/helpconfig.py\", line 104, in pytest_cmdline_parse\n    config: Config = outcome.get_result()\n                     ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1075, in pytest_cmdline_parse\n    self.parse(args)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1425, in parse\n    self._preparse(args, addopts=addopts)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1300, in _preparse\n    self._consider_importhook(args)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1204, in _consider_importhook\n    self._mark_plugins_for_rewrite(hook)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1224, in _mark_plugins_for_rewrite\n    for name in _iter_rewritable_modules(package_files):\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 863, in _iter_rewritable_modules\n    package_files = list(package_files)\n                    ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1221, in <genexpr>\n    for file in dist.files or []\n                ^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/importlib/metadata/__init__.py\", line 501, in files\n    make_files(\n  File \"/Users/bill/anaconda3/lib/python3.12/importlib/metadata/_functools.py\", line 102, in wrapper\n    return func(param, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/importlib/metadata/__init__.py\", line 494, in make_files\n    return starmap(make_file, csv.reader(lines))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: 'NoneType' object is not iterable\n"
        }
      ]
    },
    "integration": {
      "total": 0,
      "passed": 0,
      "failed": 0,
      "tests": [
        {
          "name": "test_comprehensive_system.py",
          "success": false,
          "total": 0,
          "passed": 0,
          "failed": 0,
          "skipped": 0,
          "duration": 0.0,
          "output": "",
          "errors": "Traceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pytest/__main__.py\", line 5, in <module>\n    raise SystemExit(pytest.console_main())\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 192, in console_main\n    code = main()\n           ^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 150, in main\n    config = _prepareconfig(args, plugins)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 331, in _prepareconfig\n    config = pluginmanager.hook.pytest_cmdline_parse(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_callers.py\", line 55, in _multicall\n    gen.send(outcome)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/helpconfig.py\", line 104, in pytest_cmdline_parse\n    config: Config = outcome.get_result()\n                     ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1075, in pytest_cmdline_parse\n    self.parse(args)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1425, in parse\n    self._preparse(args, addopts=addopts)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1300, in _preparse\n    self._consider_importhook(args)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1204, in _consider_importhook\n    self._mark_plugins_for_rewrite(hook)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1224, in _mark_plugins_for_rewrite\n    for name in _iter_rewritable_modules(package_files):\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 863, in _iter_rewritable_modules\n    package_files = list(package_files)\n                    ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1221, in <genexpr>\n    for file in dist.files or []\n                ^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/importlib/metadata/__init__.py\", line 501, in files\n    make_files(\n  File \"/Users/bill/anaconda3/lib/python3.12/importlib/metadata/_functools.py\", line 102, in wrapper\n    return func(param, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/importlib/metadata/__init__.py\", line 494, in make_files\n    return starmap(make_file, csv.reader(lines))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: 'NoneType' object is not iterable\n"
        }
      ]
    },
    "dashboard": {
      "total": 0,
      "passed": 0,
      "failed": 0,
      "tests": [
        {
          "name": "test_dashboard_server.py",
          "success": false,
          "total": 0,
          "passed": 0,
          "failed": 0,
          "skipped": 0,
          "duration": 0.0,
          "output": "",
          "errors": "Traceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pytest/__main__.py\", line 5, in <module>\n    raise SystemExit(pytest.console_main())\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 192, in console_main\n    code = main()\n           ^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 150, in main\n    config = _prepareconfig(args, plugins)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 331, in _prepareconfig\n    config = pluginmanager.hook.pytest_cmdline_parse(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_callers.py\", line 55, in _multicall\n    gen.send(outcome)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/helpconfig.py\", line 104, in pytest_cmdline_parse\n    config: Config = outcome.get_result()\n                     ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1075, in pytest_cmdline_parse\n    self.parse(args)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1425, in parse\n    self._preparse(args, addopts=addopts)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1300, in _preparse\n    self._consider_importhook(args)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1204, in _consider_importhook\n    self._mark_plugins_for_rewrite(hook)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1224, in _mark_plugins_for_rewrite\n    for name in _iter_rewritable_modules(package_files):\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 863, in _iter_rewritable_modules\n    package_files = list(package_files)\n                    ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1221, in <genexpr>\n    for file in dist.files or []\n                ^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/importlib/metadata/__init__.py\", line 501, in files\n    make_files(\n  File \"/Users/bill/anaconda3/lib/python3.12/importlib/metadata/_functools.py\", line 102, in wrapper\n    return func(param, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/importlib/metadata/__init__.py\", line 494, in make_files\n    return starmap(make_file, csv.reader(lines))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: 'NoneType' object is not iterable\n"
        }
      ]
    },
    "security": {
      "total": 0,
      "passed": 0,
      "failed": 0,
      "tests": [
        {
          "name": "test_security_manager.py",
          "success": false,
          "total": 0,
          "passed": 0,
          "failed": 0,
          "skipped": 0,
          "duration": 0.0,
          "output": "",
          "errors": "Traceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pytest/__main__.py\", line 5, in <module>\n    raise SystemExit(pytest.console_main())\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 192, in console_main\n    code = main()\n           ^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 150, in main\n    config = _prepareconfig(args, plugins)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 331, in _prepareconfig\n    config = pluginmanager.hook.pytest_cmdline_parse(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_callers.py\", line 55, in _multicall\n    gen.send(outcome)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/helpconfig.py\", line 104, in pytest_cmdline_parse\n    config: Config = outcome.get_result()\n                     ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1075, in pytest_cmdline_parse\n    self.parse(args)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1425, in parse\n    self._preparse(args, addopts=addopts)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1300, in _preparse\n    self._consider_importhook(args)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1204, in _consider_importhook\n    self._mark_plugins_for_rewrite(hook)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1224, in _mark_plugins_for_rewrite\n    for name in _iter_rewritable_modules(package_files):\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 863, in _iter_rewritable_modules\n    package_files = list(package_files)\n                    ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1221, in <genexpr>\n    for file in dist.files or []\n                ^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/importlib/metadata/__init__.py\", line 501, in files\n    make_files(\n  File \"/Users/bill/anaconda3/lib/python3.12/importlib/metadata/_functools.py\", line 102, in wrapper\n    return func(param, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/importlib/metadata/__init__.py\", line 494, in make_files\n    return starmap(make_file, csv.reader(lines))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: 'NoneType' object is not iterable\n"
        }
      ]
    },
    "phase": {
      "total": 0,
      "passed": 0,
      "failed": 0,
      "tests": [
        {
          "name": "test_phase_manager.py",
          "success": false,
          "total": 0,
          "passed": 0,
          "failed": 0,
          "skipped": 0,
          "duration": 0.0,
          "output": "",
          "errors": "Traceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pytest/__main__.py\", line 5, in <module>\n    raise SystemExit(pytest.console_main())\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 192, in console_main\n    code = main()\n           ^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 150, in main\n    config = _prepareconfig(args, plugins)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 331, in _prepareconfig\n    config = pluginmanager.hook.pytest_cmdline_parse(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_callers.py\", line 55, in _multicall\n    gen.send(outcome)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/helpconfig.py\", line 104, in pytest_cmdline_parse\n    config: Config = outcome.get_result()\n                     ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1075, in pytest_cmdline_parse\n    self.parse(args)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1425, in parse\n    self._preparse(args, addopts=addopts)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1300, in _preparse\n    self._consider_importhook(args)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1204, in _consider_importhook\n    self._mark_plugins_for_rewrite(hook)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1224, in _mark_plugins_for_rewrite\n    for name in _iter_rewritable_modules(package_files):\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 863, in _iter_rewritable_modules\n    package_files = list(package_files)\n                    ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1221, in <genexpr>\n    for file in dist.files or []\n                ^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/importlib/metadata/__init__.py\", line 501, in files\n    make_files(\n  File \"/Users/bill/anaconda3/lib/python3.12/importlib/metadata/_functools.py\", line 102, in wrapper\n    return func(param, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/importlib/metadata/__init__.py\", line 494, in make_files\n    return starmap(make_file, csv.reader(lines))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: 'NoneType' object is not iterable\n"
        }
      ]
    },
    "firewall": {
      "total": 0,
      "passed": 0,
      "failed": 0,
      "tests": [
        {
          "name": "test_firewall_manager.py",
          "success": false,
          "total": 0,
          "passed": 0,
          "failed": 0,
          "skipped": 0,
          "duration": 0.0,
          "output": "",
          "errors": "Traceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pytest/__main__.py\", line 5, in <module>\n    raise SystemExit(pytest.console_main())\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 192, in console_main\n    code = main()\n           ^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 150, in main\n    config = _prepareconfig(args, plugins)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 331, in _prepareconfig\n    config = pluginmanager.hook.pytest_cmdline_parse(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_callers.py\", line 55, in _multicall\n    gen.send(outcome)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/helpconfig.py\", line 104, in pytest_cmdline_parse\n    config: Config = outcome.get_result()\n                     ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1075, in pytest_cmdline_parse\n    self.parse(args)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1425, in parse\n    self._preparse(args, addopts=addopts)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1300, in _preparse\n    self._consider_importhook(args)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1204, in _consider_importhook\n    self._mark_plugins_for_rewrite(hook)\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1224, in _mark_plugins_for_rewrite\n    for name in _iter_rewritable_modules(package_files):\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 863, in _iter_rewritable_modules\n    package_files = list(package_files)\n                    ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/site-packages/_pytest/config/__init__.py\", line 1221, in <genexpr>\n    for file in dist.files or []\n                ^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/importlib/metadata/__init__.py\", line 501, in files\n    make_files(\n  File \"/Users/bill/anaconda3/lib/python3.12/importlib/metadata/_functools.py\", line 102, in wrapper\n    return func(param, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/bill/anaconda3/lib/python3.12/importlib/metadata/__init__.py\", line 494, in make_files\n    return starmap(make_file, csv.reader(lines))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: 'NoneType' object is not iterable\n"
        }
      ]
    }
  },
  "summary": {
    "total_tests": 0,
    "total_passed": 0,
    "total_failed": 0,
    "total_skipped": 0,
    "success_rate": 0
  }
}